### ISSUE TITLE
IsGameOver() misses wins that don't go all the way to the edge

### ISSUE THREAD

**Issue by FrankPudding** [FrankPudding/QuadRelate#6]
|  |  |  |  |  |  |  |
|  |  |  |  |  |  |  |
|  |  |Y|  |  |  |Y|
|Y|  |R|  |  |  |Y|
|Y|  |Y|  |  |  |R|
|Y|R|R|R|R|Y|R|
---------------

For example, this configuration does not count as a win

**Comment by vmelia** [comment]
Ok, you know the drill. 
Make a test that fails:
E.g.,
```
|E|R|R|R|R|E|R|
|R|E|R|R|R|R|E|
|Y|R|R|R|R|Y|R|
|R|Y|R|R|R|R|Y|
```
Then fix it and rerun the test.
Will you need help with the fix?

**Comment by FrankPudding** [comment]
The drill is well rehearsed. Shouldn't need any help with the fix, but thank you.
